defaults:
  - override /dataset: mind
  - override /experiment: nrms_mind_small

description: "Evaluate all models on MIND-small dataset"

# Common settings for all experiments in group
dataset:
  version: "small"

# List of models to evaluate
models:
  - nrms
  - naml

# Common training parameters
train:
  batch_size: 32
  num_epochs: 10
