_target_: src.models.crown.CROWN

# Inherit from base configuration
defaults:
- base

# Model-specific parameters

# Intent disentanglement
intent_num: 4  # Number of intents (k parameter)
intent_embedding_dim: 200
alpha: 0.5  # Weight for auxiliary category prediction loss

# Category embeddings
category_embedding_dim: 100
subcategory_embedding_dim: 100

# Attention
attention_dim: 200

# Transformer parameters
num_heads: 8
head_dim: 40  # 8 * 40 = 320 
feedforward_dim: 512
num_layers: 2

# ISAB (Induced Set Attention Block) parameters
isab_num_heads: 4
isab_num_inducing_points: 4

# GraphSAGE parameters
graph_hidden_dim: 300
graph_num_layers: 1

# Input dimensions
max_abstract_length: 100  # For processing news body/abstract

# Loss configuration
loss:
  name: "categorical_crossentropy"
  from_logits: false  # CROWN outputs probabilities after softmax

# Additional model flags
process_abstract: true  # CROWN uses both title and body
process_category: true  # CROWN uses category information
process_subcategory: true  # CROWN uses subcategory information