_target_: src.models.lstur.LSTUR

# Inherit from base configuration
defaults:
- base

# Model-specific parameters
cnn_filter_num: 300 # Number of CNN filters for news encoding
cnn_kernel_size: 3 # Kernel size for CNN
cnn_activation: "relu" # CNN activation function
attention_hidden_dim: 200 # Hidden dimension for additive attention
gru_unit: 300 # Number of GRU units for user encoder
type: "ini" # User encoder type: "ini" (initial state) or "con" (concatenation)
dropout_rate: 0.2 # Dropout rate

# User representation parameters
num_users: 100000 # Total number of users in the dataset (should be set based on actual data)
process_user_id: true # LSTUR uses user ids for embedding computation

# Loss configuration
loss:
  name: "categorical_crossentropy" # Must match our custom loss names in utils/losses.py
  from_logits: false # Whether the model outputs logits or probabilities 
