_target_: src.models.naml.NAML

# Inherit from base configuration
defaults:
- base

# Word Embedding parameters
embedding_size: 300

# News Encoder (NAMLNewsEncoder) parameters
category_embedding_dim: 100
subcategory_embedding_dim: 100
cnn_filter_num: 400 # Number of filters for CNN (output dim for title/abs after CNN)
cnn_kernel_size: 3
word_attention_query_dim: 200 # dim for word-level attention
view_attention_query_dim: 200 # dim for view-level attention
user_attention_query_dim: 200 # Hidden dim for user attention

# User Encoder (NAMLUserEncoder) parameters
user_num_attention_heads: 10 # Must be a divisor of news_embedding_dim (e.g., 200/10 = 20 head_size)

# Common parameters
dropout_rate: 0.2
seed: 42 # Model-specific seed, can be overridden by global seed
