_target_: src.models.nrms.NRMS

# Model parameters
multiheads: 16  # Number of attention heads
head_dim: 20    # Dimension of each attention head (multiheads * head_dim = 320 > 300d embeddings)
attention_hidden_dim: 200  # Hidden dimension for additive attention
dropout_rate: 0.2  # Dropout rate

# News encoder parameters
# news_encoder:
#   word_embedding_dim: ${model.word_embedding_dim}
#   num_attention_heads: ${model.num_attention_heads}
#   query_vector_dim: ${model.query_vector_dim}
#   dropout_rate: ${model.dropout_rate}

# User encoder parameters
# user_encoder:
#   num_attention_heads: ${model.num_attention_heads}
#   query_vector_dim: ${model.query_vector_dim}
#   dropout_rate: ${model.dropout_rate}
