_target_: src.datasets.custom_simple.CustomDataset

# Inherit from base configuration
defaults:
- base

# Multilingual dataset configuration examples
name: "MultilingualNews"  # Customizable dataset name
version: "v1"  # Dataset version identifier

# Language configuration - change this for your target language
language: "portuguese"  # Options: portuguese, spanish, german, french, italian, etc.

# Data location (can be path or URLs)
data_path: null  # Optional: Path to dataset directory
download_if_missing: true  # Whether to download dataset if not found

# Dataset URLs (can be null if data is local)
urls: null
# Example for Portuguese news:
# urls:
#   train: "https://your-domain.com/portuguese_news_train.zip"
#   valid: "https://your-domain.com/portuguese_news_valid.zip"

# BPEmb embedding configuration for multilingual support
embedding_type: "bpemb"  # Recommended for non-English languages
embedding_size: 300  # BPEmb supported dimensions: 25, 50, 100, 200, 300

# ID format configuration (adjust based on your dataset)
id_prefix: ""  # News ID prefix (e.g., "N" for MIND format, "" for plain numeric)
user_id_prefix: ""  # User ID prefix (e.g., "U" for MIND format, "" for plain numeric)

# Text processing parameters
word_threshold: 3  # Word frequency threshold for vocabulary building

# Dataset behavior configuration
random_train_samples: false
validation_split_strategy: "random"  # Options: chronological, random
validation_split_percentage: 0.05
validation_split_seed: 42

# Data sampling fractions
data_fraction_train: 1.0
data_fraction_val: 1.0
data_fraction_test: 1.0

# Dataset mode
mode: "train"

# Preprocessing parameters (adjust based on language characteristics)
max_title_length: 30  # May need adjustment for languages with longer words
max_abstract_length: 50  # May need adjustment for languages with longer words
max_history_length: 50
max_impressions_length: 5

# Knowledge graph configuration
use_knowledge_graph: false
max_entities: 100
max_relations: 50

# Pass sampling configuration directly
sampling: ${sampling}

# Feature processing flags
process_title: false
process_abstract: false
process_category: false
process_subcategory: false
process_user_id: false

# Language-specific examples and notes:
# 
# For Portuguese (pt):
#   language: "portuguese"
#   BPEmb will automatically use Portuguese subword embeddings
#
# For Spanish (es):
#   language: "spanish" 
#   BPEmb supports excellent Spanish coverage
#
# For German (de):
#   language: "german"
#   May need longer max_title_length due to compound words
#   max_title_length: 35
#
# For French (fr):
#   language: "french"
#   Standard settings usually work well
#
# For Italian (it):
#   language: "italian"
#   Standard settings usually work well
#
# Supported languages include:
# English, German, French, Spanish, Italian, Portuguese, Russian, Japanese, Korean,
# Chinese, Arabic, Hindi, Turkish, Polish, Dutch, Swedish, Danish, Norwegian, Finnish,
# Czech, Slovak, Hungarian, Croatian, Serbian, Bulgarian, Ukrainian, Romanian, and many more.
#
# BPEmb benefits:
# - Automatic subword tokenization for better OOV handling
# - Pre-trained on Wikipedia for 275+ languages
# - Consistent embedding space across languages
# - Automatic download and caching