extract_topics_entities:
  description: >
    Analyze the title: "{title}" and abstract: "{abstract}" and extract a list of relevant topics, entities, and keywords that should be used for downstream search and retrieval.
  expected_output: >
    A JSON object with three lists: {"topics": [...], "entities": [...], "keywords": [...]} containing the most important topics, entities, and key phrases extracted from the title and abstract, suitable for use as search queries for the Exa tool.
  agent: topic_extractor

retrieve_candidate_articles:
  description: >
    Use the Exa tool to search for approximately 15 news articles published before the publication date ({publication_date}) that are topically or contextually related to the provided list of topics, entities, and keywords. DO NOT summarize, reformat, or interpret the results.  Just return the raw output from the Exa tool as-is.
  expected_output: >
    The raw JSON output from the Exa tool, containing all articles and their metadata.
  agent: news_retriever

filter_and_rank_articles:
  description: >
    Analyze the candidate articles and select the top 4-7 that are most relevant to the original article, using both topic similarity and entity overlap.
  expected_output: >
    A ranked list of 4-7 articles, each with title, URL, and a justification for its selection.
  agent: relevance_filter

synthesize_background:
  description: >
    Using the selected articles, write a background section that explains the core idea, provides historical or contextual information, and helps readers build foundational knowledge.
  expected_output: >
    A concise, informative background section.
  agent: background_synthesizer

compose_storytelling_news:
  description: >
    Integrate the background, context, and original article into a storytelling news that makes the news more accessible and interesting.
  expected_output: >
    A story-like narrative that contextualizes the original article for readers.
  agent: storytelling_news_composer
