defaults:
- _self_
- model: nrms # default model
- dataset: mind # default dataset
- experiment: nrms_mind_small # default experiment
- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled

# Hydra configuration
hydra:
  run:
    dir: ${output_base_dir}/${name}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: ${output_base_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false  # Don't change working directory

# Basic configuration (fallback values if not specified in experiment)
seed: 42
output_base_dir: "outputs"
device:
  gpu_ids: [ 0 ] # Use all 4 GPUs
  memory_limit: 1 # Use 100% of each GPU's memory
num_workers: 4

# Default training parameters (can be overridden by experiment)
train:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.0001
  gradient_clip_val: 1.0
  early_stopping:
    patience: 5
    min_improvement: 0.01

# Default evaluation parameters (can be overridden by experiment)
eval:
  fast_evaluation: true # Whether to use fast evaluation with precomputed vectors
  batch_size: 4096 # Batch size for evaluation
  save_predictions: true # Whether to save predictions to file
  predictions_dir: "predictions" # Directory to save predictions
  run_initial_eval: false # <-- (optional, it's interesting to see performance improve, but it takes longer)
  run_test_after_training: true # <--- (optional, if you want to run test after training)

# Default logging configuration (can be overridden by experiment)
logging:
  project_name: "NewsReX"
  log_every_n_steps: 100
  enable_wandb: false
  experiment_name: ${model._target_}_${dataset.version} # This will create names like "src.models.nrms.NRMS_small"

# Metrics configuration
metrics:
  params: {} # Empty dict for default parameters
  _target_: src.utils.metrics.NewsRecommenderMetrics

# Remove or comment out the root level experiment_name since we're using the one in logging
# experiment_name: None

# Cache configuration
cache:
  root_dir: ".cache" # Hidden cache directory in project root
  clear_on_start: false # Whether to clear cache when starting training
